nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://ecstatic-saha.217-154-3-21.plesk.page', 'http://localhost:3000']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600

    paths:
        '^/api/':
            allow_origin: ['https://ecstatic-saha.217-154-3-21.plesk.page', 'http://localhost:3000']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
            allow_credentials: true
